from db_engine import Engine
from models.Common import Base

from models.Movie import Movie
from models.Genres import Genres
from models.GenreOfFilm import GenreOfFilm
from models.FilmDirector import FilmDirector
from models.FilmCast import FilmCast
from models.MovieReview import MovieReview
from models.User import User
from models.Person import Person
from models.WishList import Wishlist
from models.Watchlist import Watchlist
from models.BannedList import BannedList
from models.Subscription import Subscription

import os


if os.path.exists('filmfinder_tahelka.db'):
    os.remove('filmfinder_tahelka.db')

Base.metadata.create_all(Engine)
os.system('python3 data_migration.py')

from RecSystem.movie_movie import readWriteComputeMoviePred
readWriteComputeMoviePred()

# other import statements are here because they all need 'movie_movie.csv' generated by 'readWriteComputeMoviePred'
from RecSystem.user_movie import readWriteComputeUserPred
from RecSystem.director_movie import readWriteComputeDirectorPred
from RecSystem.genre_movie import readWriteComputeGenrePred

readWriteComputeUserPred()
readWriteComputeGenrePred()
readWriteComputeDirectorPred()